name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build OuvertSpades
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
